### ISSUE TITLE
Make Kraken2 build module

### ISSUE THREAD

**Issue by jfy133** [nf-core/createtaxdb#13]

**Comment by jfy133** [comment]
@alxndrdiaz is currently making these modules as per https://github.com/nf-core/modules/issues/2953

**Comment by Midnighter** [comment]
@alxndrdiaz please also [take a look here](https://github.com/Midnighter/kraken2-bracken-test-db/) for some inspiration. It's definitely outdated module structure, though.

**Comment by jfy133** [comment]
Draft subworkflow: https://github.com/nf-core/modules/pull/5407
