### ISSUE TITLE
MALT will fail if too many FASTAs due to UNIX command limits

### ISSUE THREAD

**Issue by jfy133** [nf-core/createtaxdb#29]
### Description of the bug

See here: https://nfcore.slack.com/archives/C062H82UCRG/p1710513463929289?thread_ts=1709737644.063319&cid=C062H82UCRG

I think we can just supply the entire work directory to the command with `./` or stage them into a directory

**Comment by Midnighter** [comment]
Alternatively, does Malt accept as input a file listing all the FASTA?

**Comment by jfy133** [comment]
Sadly not

**Comment by jfy133** [comment]
Should probably update ALL modules to do this if they support it...

**Comment by jfy133** [comment]
Module tweaks:

- MALT: use directory input
- Centrifuge: takes a list, but no directory support. Recommendation is to stick into a single file: https://github.com/DaehwanKimLab/centrifuge/issues/116 [check if we collapse into one already? like in DIAMOND]
- ganon: use the `--input-file`

No change required:

- Bracken: takes in directory already
-  DIAMOND: takes in only a single file anyway
- Kajiu: only takes in a a single file
- Karken2: already dealt with with xargs (but in 'single file input' module? Check)
- Krakenuniq only takes a single file

**Comment by Midnighter** [comment]
We do we already use `collate` in front of all of these? That would anyway be a good idea, so that we have batches but still parallelize.

**Comment by jfy133** [comment]
> We do we already use `collate` in front of all of these? That would anyway be a good idea, so that we have batches but still parallelize.

Batches for what exactly? I don't think you can 'merge' databases in most if not all...?

**Comment by jfy133** [comment]
Now I think about it maybe could just stick all input genomes into a single file in all cases (would need to check if that works with ganon), as we already forced to do this for quite a few tools (despite my fears of generating a redundant mega fasta file TB in size)

**Comment by Midnighter** [comment]
> > We do we already use `collate` in front of all of these? That would anyway be a good idea, so that we have batches but still parallelize.
> 
> Batches for what exactly? I don't think you can 'merge' databases in most if not all...?

Ah, sourmash can do it and for kraken2 you can at least assemble the library in separate steps, but it then has to process k-mers in one go, that's true.

**Comment by jfy133** [comment]
> > > We do we already use `collate` in front of all of these? That would anyway be a good idea, so that we have batches but still parallelize.
> > 
> > Batches for what exactly? I don't think you can 'merge' databases in most if not all...?
> 
> Ah, sourmash can do it and for kraken2 you can at least assemble the library in separate steps, but it then has to process k-mers in one go, that's true.

Ah ok. Yeah sourmash (still 🥲) isn't in taxprofiler yet, and kraken2 is already basically paralelised already as you can only add one genome at a time (before the building) Indeed, but we already handle that in the module with xargs iirc

**Comment by jfy133** [comment]
So I think actually the best approach is for everything to just concatenate into one mega FASTA by default.

From my notes above it looks like it's just Kraken2 is possibly a question mark there

**Comment by jfy133** [comment]
Separate information though, accepts GZIPped input?:

1. bracken: NA
2. centrifuge: NO (single preferred)
3. diamond: YES (single)
4. kaiju:
5. kraken2: NO (single or multiple)
6. krakenuniq: SEEMS NO (multiple)
7. malt: YES (single, multiple, or directory)
