### ISSUE TITLE
How to build standard databases?

### ISSUE THREAD

**Issue by ChillarAnand** [nf-core/createtaxdb#40]
### Description of the bug

To build kraken2 database, we can directly run

```
$ kraken2-build --standard --threads 24 --db $DBNAME
```

This will build the standard database by default.

How should input file be created to create standard databases?

### Command used and terminal output

```console
$ nextflow run nf-core/createtaxdb -r dev --input i.csv --outdir k2s --dbname kraken2
```

**Comment by jfy133** [comment]
Hi @ChillarAnand 

Thanks for the question!

The primary purpose of createtaxdb is to create custom databases rather than standard databases you can download in a 'one shot'.

I don't plan to support such functionality currently, because as in your example, you just need to run a single command without requiring any input files, which should be simple enough without the need of a pipeline.

**Comment by jfy133** [comment]
Feel free to reopen if you have a strong case for including it.

**Comment by ChillarAnand** [comment]
I was trying to build a custom db but got stuck. So I was trying to build a standard db.

Here is a sample file as per docs.

```
❯ cat in.csv
sample,fastq_1,fastq_2
test,/home/anand/avilpage/BS006840.fastq,
```

When I run the below command it is failing with 

```
❯ nextflow run nf-core/createtaxdb -r dev --input in.csv --outdir k2_db --dbname kraken2

...
------------------------------------------------------
ERROR ~ ERROR: Validation of 'input' file failed!

 -- Check '.nextflow.log' file for details
The following errors have been detected:

* -- Entry 1: Missing required value: fasta_dna
* -- Entry 1: Missing required value: fasta_aa
* -- Entry 1: Missing required value: id
* -- Entry 1: Missing required value: taxid
*
```

From the docs, I am not able to figure out the issue.

**Comment by jfy133** [comment]
Sorry I missed your comment here @ChillarAnand !


The input sheet should be 4 columns:

Id: name of the genome/sequence 
Taxid: the corresponding taxid to your genome (must correspond to your tax dump files)
Fasta_dna: path to a a nucleotide sequence fasta of your genome (when using DNA based profile lling tools
Fasta_aa: path to an amino acid nucleotide sequence of your genome (when using protein sequence profiling tools)
