### ISSUE TITLE
Documentation outdated

### ISSUE THREAD

**Issue by ChillarAnand** [nf-core/createtaxdb#41]
### Description of the bug

Docs show that input file should have 3 columns. https://nf-co.re/createtaxdb/dev/docs/usage/#full-samplesheet

However, when the workflow is run, it is failing with validation error.

https://github.com/nf-core/createtaxdb/issues/40#issuecomment-2218000081

**Comment by jfy133** [comment]
Thanks @ChillarAnand !

The pipeline is not yet released and is only barely just in the alpha stage, thus there is no documentation yet - I'm not 100% set on the input structure etc. What you prefer to is boilerplate code.

I'm still on parental leave until September, but after this development will accelerate

**Comment by ChillarAnand** [comment]
Understood, @jfy133 

Thanks for your efforts to streamline db building.

Most of the time fasta files are downloaded from refseq or any other source which has tax id.

It would be great if pipeline can auto detect tax id from file instead of asking users to construct separate file.

**Comment by jfy133** [comment]
Also note @ChillarAnand that I replied on the other issue describing how to (currently) format the tsv :)

**Comment by ChillarAnand** [comment]
Is it possible to update the databases incrementally?

**Comment by jfy133** [comment]
> Is it possible to update the databases incrementally?

Essentially no. Very few of the tools support this sadly, so I've not currently considered this for those that do.
